### PR TITLE
Fogl 2947: first version

### PR DESCRIPTION
**Pull request by sstefano69**
version  installed 

image

### CODE REVIEW

**Comment by AmandeepArora** [comment]
@sstefano69 - Can you please state the purpose of this repo? Can't we just use the libcurl-dev package for building our code against?

**Comment by sstefano69** [comment]
> @sstefano69 - Can you please state the purpose of this repo? Can't we just use the libcurl-dev package for building our code against?

@AmandeepArora 
the curl version in Centos is old 7.29 and does not support Kerberos GSS-API so we have to update it

we just install  'yum install -y curl-devel' in Ubuntu.


Screenshot - 19-Aug-19 , 12_10_42

**Comment by AmandeepArora** [comment]
So we use this repo only for centos/RHEL? And for other platforms, we install using apt?

Even for centos/RHEL, can we keep libcurl in compiled form, since that would be only around 20-25 files (libraries and headers) compared to 3000+ files here. We could even statically link with libcurl.a.

**Comment by MarkRiddoch** [comment]
> > @sstefano69 - Can you please state the purpose of this repo? Can't we just use the libcurl-dev package for building our code against?
> 
> @AmandeepArora
> the curl version in Centos is old 7.29 and does not support Kerberos GSS-API so we have to update it
> 
> we just install 'yum install -y curl-devel' in Ubuntu.
> 
> Screenshot - 19-Aug-19 , 12_10_42

Could you mention this in the README so that we have a record of why it was done and for which platforms.

**Comment by sstefano69** [comment]
we will download the sources directly from https://github.com/curl/curl/releases

**Pull request closed without merging**
